Task1
i-pankrat/formal-lang-course pull request #1
Opened 2023-09-10 13:06 UTC by i-pankrat

2023-09-13 17:53 UTC, vadyushkins requested changes

2023-09-13 17:53 UTC, vadyushkins commented on .github/workflows/CI.yml
> +    runs-on: ubuntu-latest
Добавьте windows, macos

2023-09-13 17:53 UTC, vadyushkins commented on tests/test_graphs_lib.py
> +    )
Создайте файл .dot и проверяйте, что то, что вы сохраняете совпадает с этим файлом

2023-09-14 10:45 UTC, i-pankrat commented on .github/workflows/CI.yml
> +    runs-on: ubuntu-latest
Добавил

2023-09-14 10:46 UTC, i-pankrat commented on tests/test_graphs_lib.py
> +    )
Поправил. Полагаю сравнить файлы лучше просто потому, что это делается легче?

2023-09-15 19:14 UTC, vadyushkins commented on tests/test_graphs_lib.py
> +    )
Это в принципе правильный подход, когда вы проверяете, что функция, которая что-то выдает, выдает именно то, что вы ожидаете

2023-09-15 19:17 UTC, vadyushkins requested changes

2023-09-15 19:17 UTC, vadyushkins commented on tests/test_graphs_lib.py
> +    )
У вас в tests/static должен появиться файл expected_graph.dot

2023-09-15 19:17 UTC, vadyushkins commented on tests/test_graphs_lib.py
> +    assert filecmp.cmp(full_file_name, full_expected_file_name)
shallow=False

и подумайте в чем тут проблема

2023-09-16 07:22 UTC, i-pankrat commented on tests/test_graphs_lib.py
> +    assert filecmp.cmp(full_file_name, full_expected_file_name)
С опцией shallow проблема была в том, что файл на самом деле не читался и не проверялось именно его содержимое.

2023-09-20 07:13 UTC, vadyushkins commented on tests/test_graphs_lib.py
> +    assert filecmp.cmp(full_file_name, full_expected_file_name)
Не совсем так. Так как файлы вы создаете новые, то метаданные у них разные и содержимое все-таки сравнивается явно. Однако, в случае, если метаданные подставлены одинаковые, а содержимое разное, такая функция может выдавать True, что является неожиданным поведением, чего лучше избегать.

2023-09-20 07:13 UTC, vadyushkins approved these changes

2023-09-21 15:33 UTC, merged